# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Enter a book title.', max_length=1000),
        ),
    ]
