# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170627_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the book.', max_length=2000),
        ),
    ]
